### ISSUE TITLE
Pulling parts of the schema out into variables

### ISSUE THREAD

**Issue by atroche** [miner/herbert#12]
Hi,

The schema I'm building is pretty big, and it'd be nice to build it up out of named parts rather than just having a single large map.

To take a small example, instead of doing…

```clojure
(def author
  '{:name   str
    :email  str
    :locale '(or "en" "jp" "de")})
```

I'd like to do:

```clojure
(def locale '(or "en" "jp" "de"))

(def author
  '{:name   str
    :email  str
    :locale locale})
```

But I can't find a way to do this. Any tips would be much appreciated!

Cheers.

**Comment by atroche** [comment]
So far the only way I have of doing this is:
```clojure
(def author
  `{:name   ~'str
    :email  ~'str
    :locale ~locale})
```

Which is pretty ugly…

**Comment by atroche** [comment]
Ah, I found your link to backtick in this issue, and using its template macro I can do:

```clojure
(def author
  (template {:name   str
             :email  str
             :locale ~locale}))
```

I'm surprised this isn't a use case you've come across in your own work, @miner. What do you do for large schemas?

**Comment by miner** [comment]
The (grammar ...) pattern lets you give names to subparts of a schema.  You can also merge-schema to share grammar "rules".  I use Backtick template to make use of other Clojure data in schemas.
