### ISSUE TITLE
Conditional on bound value

### ISSUE THREAD

**Issue by atroche** [miner/herbert#13]
I'm looking to do something like this:

```clojure
(def number
  '{:foo-number (:= IsFooNumber true)
    :number     (if IsFooNumber
                  (in (int 1 10))
                  int)})
```

…where I can generate and bind a value, and use that to choose what another part of the data structure should look like. I'm currently having no problem doing that using `bind` in `test.check`, but I was really hoping I could find a declarative way of expressing it.

Is that possible?

**Comment by miner** [comment]
Herbert can use := bound values to parameterize some matches, but it doesn't have conditional tests.  In this situation, I think you're better off using test.check bind to code your generator.
