### ISSUE TITLE
List of related projects not helpful

### ISSUE THREAD

**Issue by rmoehn** [miner/herbert#15]
The README [lists](https://github.com/miner/herbert#related-projects) a number of projects one can look at if Herbert is not exactly what one is looking for. However, developers who aren't experienced in the space *don't know* what exactly they're looking for.

Imagine you've lived in the city for all your life and now move to the countryside. You go to the small hardware shop nearby and ask for a lawnmower. They tell you about this one type that they have in store and which is in the box over there, »but if it's not exactly what you're looking for, you can also order one of these«, presenting you with the data sheets for some similar gardening tools they can order. The data sheets have some text and tables of technical data, but no pictures (or maybe only of cats running away). Now, what exactly were you looking for? A little comparison would be sooo helpful.

**Comment by miner** [comment]
I certainly agree that it would be useful to have *someone* provide a detailed comparison of all the projects in this space.  However, it would be a significant amount of work to do a proper comparison, and that is not something I want to work on at the moment.  I've got other priorities.

If someone wanted to put together such a comparison, I would answer questions about Herbert.  The Clojure mailing list would be a good place to ask other people about their experiences with various schema libraries.

**Comment by rmoehn** [comment]
Oh, I wasn't asking for a *detailed* comparison of *all* the projects. Just one or two sentences each for the items already on your list about how they compare to Herbert. Since you wrote the library, you know about different needs and tradeoffs etc., so it shouldn't take that long.

The list as it is now is more confusing than it is helpful: if I know what I'm looking for, I can find it through some search engine. If I naively searched for "schema" and find your library, I'm happy for thirty seconds that I found a great schema library, »exactly what I was looking for!«, until I hit the list and am suddenly puzzled and paralyzed. Choice can be a curse.
