### ISSUE TITLE
support generators for grammar pattern

### ISSUE THREAD

**Issue by norton** [miner/herbert#17]
Have grammar pattern generators been excluded on purpose?
 
If not, would the generators have support for recursively defined grammars?

**Comment by miner** [comment]
Just not implemented yet.  I'm reworking the code in a private branch to make it more extensible.  Eventually, I hope to support the recursive generators.

**Comment by norton** [comment]
Okay, thank you.  Do you have a timeframe for releasing such features?

If it is helpful, I have some experience implementing recursive generators for ABNF grammars in Erlang and QuickCheck.

**Comment by miner** [comment]
I'm going to work on this today.  If you have examples that you want me to test, please post here.

**Comment by norton** [comment]
Thank you but I'm new to Clojure so I don't have any examples.  I'm still learning.

**Comment by miner** [comment]
I have it grammar with recursive rules working on the 'meth' branch.  I'll probably make a proper release next week.

**Comment by miner** [comment]
v 0,7,0-alpha1 supports generators from grammars and recursive rules

**Comment by norton** [comment]
Okay, great.  Thank you.
