### ISSUE TITLE
Allow map keys of type string to be optional too

### ISSUE THREAD

**Issue by jeluard** [miner/herbert#18]
By using the `?` suffix `keyword` keys of map literal can be made optional. Would it make sense to extend this to `string` keys too?

e.g.
```clojure
(h/conforms? '{"a?" int} '{})
; true

; same as
(h/conforms? '{:a? int} '{})
; true
```

A concrete use case is validating maps received as JSON.

**Comment by miner** [comment]
On the other hand, I get some complaints about the special interpretation of the ?-suffix on keywords.  It's convenient but not obvious to some users.

As far as the string? suggestions goes... At this point, it would be a backwards-incompatible change to do special processing on string keys. I'm going to have to say no.

The un-sugared (? ...) notation should work for strings.

```clojure
(h/conforms? '{(? "a") int} {})
; true
```

You could probably write a macro to walk the Herbert pattern looking for string literals and converting the notation to get the desired result.

**Comment by jeluard** [comment]
The backwards-incompatibility argument makes sense. Thanks for the suggestion!
